apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - name: "result-service"
      nodePort: 31002
      port: 8082
      targetPort: 80
  selector:
    app: result